<?php
 
$installer = $this;

/**
 * Prepare database before module installation
 */
$installer->startSetup();
$entityTypeId = 4;


$installer->removeAttribute($entityTypeId, 'exito1');
$installer->removeAttribute($entityTypeId, 'exito');
$installer->removeAttribute($entityTypeId, 'exito2');


$installer->addAttributeGroup('catalog_product', 'Default', 'Bogota', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Bucaramanga', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Cali', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Cartagena', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Cucuta', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Envigado', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Ibague', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Manizales', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Medellin', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Monteria', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Neiva', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Pasto', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Pereira', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Sabaneta', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Santa Marta', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Villavicencio', 99);


$installer->applyAllDataUpdates();

$installer->addAttribute($entityTypeId, 'exito1', array(
    'group'             => 'Armenia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'olimpica1', array(
    'group'             => 'Armenia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour1', array(
    'group'             => 'Armenia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla1', array(
    'group'             => 'Armenia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores1', array(
    'group'             => 'Armenia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global1', array(
    'group'             => 'Armenia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la141', array(
    'group'             => 'Armenia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));





$installer->addAttribute($entityTypeId, 'exito', array(
    'group'             => 'Apartado',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'olimpica', array(
    'group'             => 'Apartado',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour', array(
    'group'             => 'Apartado',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla', array(
    'group'             => 'Apartado',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores', array(
    'group'             => 'Apartado',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global', array(
    'group'             => 'Apartado',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la14', array(
    'group'             => 'Apartado',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));






$installer->addAttribute($entityTypeId, 'exito2', array(
    'group'             => 'Barranquilla',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'olimpica2', array(
    'group'             => 'Barranquilla',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour2', array(
    'group'             => 'Barranquilla',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla2', array(
    'group'             => 'Barranquilla',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores2', array(
    'group'             => 'Barranquilla',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global2', array(
    'group'             => 'Barranquilla',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la142', array(
    'group'             => 'Barranquilla',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));




$installer->addAttribute($entityTypeId, 'exito3', array(
    'group'             => 'Bogota',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'olimpica3', array(
    'group'             => 'Bogota',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour3', array(
    'group'             => 'Bogota',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla3', array(
    'group'             => 'Bogota',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores3', array(
    'group'             => 'Bogota',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global3', array(
    'group'             => 'Bogota',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la143', array(
    'group'             => 'Bogota',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));



$installer->addAttribute($entityTypeId, 'exito4', array(
    'group'             => 'Bucaramanga',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'olimpica4', array(
    'group'             => 'Bucaramanga',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour4', array(
    'group'             => 'Bucaramanga',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla4', array(
    'group'             => 'Bucaramanga',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores4', array(
    'group'             => 'Bucaramanga',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global4', array(
    'group'             => 'Bucaramanga',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la144', array(
    'group'             => 'Bucaramanga',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));



$installer->addAttribute($entityTypeId, 'exito5', array(
    'group'             => 'Cali',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'olimpica5', array(
    'group'             => 'Cali',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour5', array(
    'group'             => 'Cali',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla5', array(
    'group'             => 'Cali',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores5', array(
    'group'             => 'Cali',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global5', array(
    'group'             => 'Cali',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la145', array(
    'group'             => 'Cali',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'exito6', array(
    'group'             => 'Cartagena',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'olimpica6', array(
    'group'             => 'Cartagena',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour6', array(
    'group'             => 'Cartagena',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla6', array(
    'group'             => 'Cartagena',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores6', array(
    'group'             => 'Cartagena',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global6', array(
    'group'             => 'Cartagena',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la146', array(
    'group'             => 'Cartagena',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'exito7', array(
    'group'             => 'Cucuta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'olimpica7', array(
    'group'             => 'Cucuta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour7', array(
    'group'             => 'Cucuta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla7', array(
    'group'             => 'Cucuta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores7', array(
    'group'             => 'Cucuta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global7', array(
    'group'             => 'Cucuta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la147', array(
    'group'             => 'Cucuta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'exito8', array(
    'group'             => 'Envigado',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'olimpica8', array(
    'group'             => 'Envigado',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour8', array(
    'group'             => 'Envigado',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla8', array(
    'group'             => 'Envigado',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores8', array(
    'group'             => 'Envigado',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global8', array(
    'group'             => 'Envigado',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la148', array(
    'group'             => 'Envigado',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));



$installer->addAttribute($entityTypeId, 'exito9', array(
    'group'             => 'Ibague',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'olimpica9', array(
    'group'             => 'Ibague',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour9', array(
    'group'             => 'Ibague',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla9', array(
    'group'             => 'Ibague',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores9', array(
    'group'             => 'Ibague',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global9', array(
    'group'             => 'Ibague',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la149', array(
    'group'             => 'Ibague',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));




$installer->addAttribute($entityTypeId, 'exito10', array(
    'group'             => 'Manizales',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'olimpica10', array(
    'group'             => 'Manizales',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour10', array(
    'group'             => 'Manizales',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla10', array(
    'group'             => 'Manizales',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores10', array(
    'group'             => 'Manizales',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global10', array(
    'group'             => 'Manizales',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1410', array(
    'group'             => 'Manizales',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));



$installer->addAttribute($entityTypeId, 'exito11', array(
    'group'             => 'Medellin',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'olimpica11', array(
    'group'             => 'Medellin',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour11', array(
    'group'             => 'Medellin',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla11', array(
    'group'             => 'Medellin',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores11', array(
    'group'             => 'Medellin',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global11', array(
    'group'             => 'Medellin',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1411', array(
    'group'             => 'Medellin',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));




$installer->addAttribute($entityTypeId, 'exito12', array(
    'group'             => 'Monteria',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'olimpica12', array(
    'group'             => 'Monteria',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour12', array(
    'group'             => 'Monteria',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla12', array(
    'group'             => 'Monteria',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores12', array(
    'group'             => 'Monteria',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global12', array(
    'group'             => 'Monteria',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1412', array(
    'group'             => 'Monteria',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));





$installer->addAttribute($entityTypeId, 'exito13', array(
    'group'             => 'Neiva',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));



$installer->addAttribute($entityTypeId, 'olimpica13', array(
    'group'             => 'Neiva',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour13', array(
    'group'             => 'Neiva',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla13', array(
    'group'             => 'Neiva',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores13', array(
    'group'             => 'Neiva',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global13', array(
    'group'             => 'Neiva',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1413', array(
    'group'             => 'Neiva',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));




$installer->addAttribute($entityTypeId, 'exito14', array(
    'group'             => 'Pasto',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));




$installer->addAttribute($entityTypeId, 'olimpica14', array(
    'group'             => 'Pasto',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour14', array(
    'group'             => 'Pasto',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla14', array(
    'group'             => 'Pasto',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores14', array(
    'group'             => 'Pasto',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global14', array(
    'group'             => 'Pasto',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1414', array(
    'group'             => 'Pasto',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));





$installer->addAttribute($entityTypeId, 'exito15', array(
    'group'             => 'Pereira',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));




$installer->addAttribute($entityTypeId, 'olimpica15', array(
    'group'             => 'Pereira',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour15', array(
    'group'             => 'Pereira',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla15', array(
    'group'             => 'Pereira',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores15', array(
    'group'             => 'Pereira',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global15', array(
    'group'             => 'Pereira',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1415', array(
    'group'             => 'Pereira',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));



$installer->addAttribute($entityTypeId, 'exito16', array(
    'group'             => 'Sabaneta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'olimpica16', array(
    'group'             => 'Sabaneta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour16', array(
    'group'             => 'Sabaneta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla16', array(
    'group'             => 'Sabaneta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores16', array(
    'group'             => 'Sabaneta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global16', array(
    'group'             => 'Sabaneta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1416', array(
    'group'             => 'Sabaneta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));





$installer->addAttribute($entityTypeId, 'exito17', array(
    'group'             => 'Santa Marta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));




$installer->addAttribute($entityTypeId, 'olimpica17', array(
    'group'             => 'Santa Marta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour17', array(
    'group'             => 'Santa Marta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla17', array(
    'group'             => 'Santa Marta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores17', array(
    'group'             => 'Santa Marta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global17', array(
    'group'             => 'Santa Marta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1417', array(
    'group'             => 'Santa Marta',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'exito18', array(
    'group'             => 'Villavicencio',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));



$installer->addAttribute($entityTypeId, 'olimpica18', array(
    'group'             => 'Villavicencio',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour18', array(
    'group'             => 'Villavicencio',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla18', array(
    'group'             => 'Villavicencio',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores18', array(
    'group'             => 'Villavicencio',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global18', array(
    'group'             => 'Villavicencio',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1418', array(
    'group'             => 'Villavicencio',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));



$installer->endSetup();