<?php
 
$installer = $this;

/**
 * Prepare database before module installation
 */
$installer->startSetup();
$entityTypeId = 4;


$installer->addAttributeGroup('catalog_product', 'Default', 'Magange', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Caucasia', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Yopal', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Ocaña', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Fusagasuga', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Sincelejo', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Guatapuri', 99);
$installer->addAttributeGroup('catalog_product', 'Default', 'Chia', 99);

$installer->applyAllDataUpdates();

$installer->addAttribute($entityTypeId, 'exito45', array(
    'group'             => 'Magange',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'olimpica45', array(
    'group'             => 'Magange',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour45', array(
    'group'             => 'Magange',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla45', array(
    'group'             => 'Magange',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores45', array(
    'group'             => 'Magange',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global45', array(
    'group'             => 'Magange',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1445', array(
    'group'             => 'Magange',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));







$installer->addAttribute($entityTypeId, 'exito46', array(
    'group'             => 'Caucasia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'olimpica46', array(
    'group'             => 'Caucasia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour46', array(
    'group'             => 'Caucasia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla46', array(
    'group'             => 'Caucasia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores46', array(
    'group'             => 'Caucasia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global46', array(
    'group'             => 'Caucasia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1446', array(
    'group'             => 'Caucasia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));




$installer->addAttribute($entityTypeId, 'exito47', array(
    'group'             => 'Yopal',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'olimpica47', array(
    'group'             => 'Yopal',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour47', array(
    'group'             => 'Yopal',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla47', array(
    'group'             => 'Yopal',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores47', array(
    'group'             => 'Yopal',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global47', array(
    'group'             => 'Yopal',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1447', array(
    'group'             => 'Yopal',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));



$installer->addAttribute($entityTypeId, 'exito48', array(
    'group'             => 'Ocaña',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'olimpica48', array(
    'group'             => 'Ocaña',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour48', array(
    'group'             => 'Ocaña',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla48', array(
    'group'             => 'Ocaña',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores48', array(
    'group'             => 'Ocaña',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global48', array(
    'group'             => 'Ocaña',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1448', array(
    'group'             => 'Ocaña',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));



$installer->addAttribute($entityTypeId, 'exito49', array(
    'group'             => 'Fusagasuga',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'olimpica49', array(
    'group'             => 'Fusagasuga',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour49', array(
    'group'             => 'Fusagasuga',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla49', array(
    'group'             => 'Fusagasuga',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores49', array(
    'group'             => 'Fusagasuga',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global49', array(
    'group'             => 'Fusagasuga',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1449', array(
    'group'             => 'Fusagasuga',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'exito50', array(
    'group'             => 'Sincelejo',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'olimpica50', array(
    'group'             => 'Sincelejo',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour50', array(
    'group'             => 'Sincelejo',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla50', array(
    'group'             => 'Sincelejo',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores50', array(
    'group'             => 'Sincelejo',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global50', array(
    'group'             => 'Sincelejo',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1450', array(
    'group'             => 'Sincelejo',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'exito51', array(
    'group'             => 'Guatapuri',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'olimpica51', array(
    'group'             => 'Guatapuri',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour51', array(
    'group'             => 'Guatapuri',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla51', array(
    'group'             => 'Guatapuri',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores51', array(
    'group'             => 'Guatapuri',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global51', array(
    'group'             => 'Guatapuri',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1451', array(
    'group'             => 'Guatapuri',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'exito52', array(
    'group'             => 'Chia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'exito',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'olimpica52', array(
    'group'             => 'Chia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'olimpica',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carrefour52', array(
    'group'             => 'Chia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carrefour',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'carulla52', array(
    'group'             => 'Chia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'carulla',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'distribuidores52', array(
    'group'             => 'Chia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'distribuidores',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->addAttribute($entityTypeId, 'global52', array(
    'group'             => 'Chia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'Global gourmet',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));


$installer->addAttribute($entityTypeId, 'la1452', array(
    'group'             => 'Chia',
    'type'              => 'text',
    'backend'           => '',
    'frontend'          => '',
    'label'             => 'La 14',
    'input'             => 'textarea',
    'class'             => '',
    'source'            => '',
    'global'            => 0,
    'visible'           => true,
    'required'          => false,
    'user_defined'      => true,
    'default'           => '',
    'searchable'        => false,
    'filterable'        => false,
    'comparable'        => false,
    'visible_on_front'  => true,
    'unique'            => false,
    'is_configurable'   => false,
));

$installer->endSetup();