<?php
/**
 * @category	design
 * @package		base_default
 * @copyright	Kreativkonzentrat GbR 2012
 *
 * Date: 04.03.12, 12:55
 */
?>
<?php if (Mage::getStoreConfig('glossary/replacings/show_empty') == 0) : ?>
	<?php $letters = $this->buildNavigation(); ?>

	<div class="glossary_navigation">
		<?php foreach ($letters as $_letter) : ?>
			<span><a href="<?php echo Mage :: app()->getStore()->getUrl('glossary')?>view/letter/<?php echo $_letter; ?>" title="<?php echo $this->__('All entries starting with %s', $_letter) ?>"><?php echo $_letter; ?></a></span>
		<?php endforeach; ?>
	</div>

<?php else : ?>
	<?php 
	$letters = array();
	$letters = range('A', 'Z');
	array_unshift($letters, "123");	
	$letters2 = $this->buildNavigation(); ?>
	<div class="glossary_navigation">
		<?php foreach ($letters as $_letter) : ?>
			<?php if (in_array($_letter, $letters2)): ?>
				<span><a href="<?php echo Mage::app()->getStore()->getUrl('glossary')?>view/letter/<?php echo $_letter; ?>" title="<?php echo $this->__('All entries starting with %s', $_letter) ?>"><?php echo $_letter; ?></a></span>
			<?php else : ?>
				<span><?php echo $_letter; ?></span>
			<?php endif; ?>
		<?php endforeach; ?>
	</div>
<?php endif; ?>
