      <div id="content_ppal">
        <div id="tit_noticias"></div>
        
<?php $items = $this->getNewsItems() ?>
<?php foreach ($items as $item): ?>
        <div id="bloque_noticia">
          <div id="bloque_noticia_superior">
<div class="news-item">
    <? if ($item->getImageShortContentShow() == 1 && $item->getImageShortContent()): ?>
    <?
        $width_max = Mage::getStoreConfig('clnews/news/shortdescr_image_max_width');
        $height_max = Mage::getStoreConfig('clnews/news/shortdescr_image_max_height');
        if (Mage::getStoreConfig('clnews/news/resize_to_max') == 1) {
            $width = $width_max;
            $height = $height_max;
        } else {
            $imageObj = new Varien_Image(Mage::getBaseDir('media') . DS . $item->getImageShortContent());
            $original_width = $imageObj->getOriginalWidth();
            $original_height = $imageObj->getOriginalHeight();
            if ($original_width > $width_max) {
                $width = $width_max;
            } else {
                $width = $original_width;
            }
            if ($original_height > $height_max) {
                $height = $height_max;
            } else {
                $height = $original_height;
            }
        }
        if ($item->getShortWidthResize()): $width = $item->getShortWidthResize(); else: $width; endif;
        if ($item->getShortHeightResize()): $height = $item->getShortHeightResize(); else: $height; endif;
    ?>
        <div class="news_image"><img src="<?php echo @Mage::helper('clnews')->resizeImage(str_replace('clnews/', '', $item->getImageShortContent()), $width, $height, 'clnews'); ?>" /></div>
    <? endif; ?>
    <h5><a href="<?php echo $item->getUrl($this->getCategory()) ?>" ><?php echo $item->getTitle();?></a></h5>
    <?php if (Mage::helper('clnews')->showDate()): ?>
        <?php if (Mage::helper('clnews')->showTime()): ?>
            <span class="date"><?php echo Mage::helper('core')->formatDate($item->getNewsTime(), true) ?></span>
        <? else: ?>
        <? $date = Mage::helper('core')->formatDate($item->getNewsTime(), true); ?>
        <? $pos = strpos($date, ' '); ?>
        <? $date = substr($date, 0, $pos);?>
            <span class="date"><?php echo $date; ?></span>
        <? endif; ?>
    <?php endif ?>
    <?php if ($item->getAuthor()): ?>
    <span class="date">&nbsp;<?php if (Mage::helper('clnews')->showAuthor()): ?>|&nbsp; <?php echo $item->getAuthor() ?><?php endif;?></span>
    <?php endif ?>
    <div class="description">
        <?php echo $item->getShortContent(); ?>

        <? if(Mage::helper('clnews')->enableLinkRoute()): ?>
        <? if($link = Mage::helper('clnews')->getLinkRoute()): ?>
            <p><a href="<?php echo $item->getUrl($this->getCategory()) ?>" class="more"><?php echo $link . '&raquo;';?></a></p>
        <? else: ?>
            <p><a href="<?php echo $item->getUrl($this->getCategory()) ?>" class="more"><?php echo $this->__('view more') . '&raquo;';?></a></p>
        <? endif; ?>
    <? endif; ?>
    </div>
    <div class="read-more">
        <a href="<?php echo $item->getUrl($this->getCategory()) ?>" >Leer más</a>
    </div>
    
    <div> </div>
            </div>
          </div>
          <div id="bloque_noticia_inferior"></div>
        </div>

<?php endforeach; ?>
</div>

<?php if($this->getLastPageNum()>1): ?>
<div id="paginador">
   <div id="paginas">
    <?php if (!$this->isFirstPage()): ?>
        <a href="<?php echo $this->getPreviousPageUrl() ?>"><?php echo $this->__('Previous') ?></a>
    <?php endif;?>
    <?php foreach ($this->getPages() as $_page): ?>
        <?php if ($this->isPageCurrent($_page)): ?>
            <span><?php echo $_page ?></span>
        <?php else: ?>
            <a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a>
        <?php endif ?>
    <?php endforeach; ?>
    <?php if (!$this->isLastPage()): ?>
        <a href="<?php echo $this->getNextPageUrl() ?>"><?php echo $this->__('Next') ?></a>
    <?php endif ?>
    </p>
</div>
<?php endif;?>
