<?php
if(Mage::getStoreConfig('easy_tabs/custom/customtabid1')){
	$method = 'get' . ucfirst(Mage::getStoreConfig('easy_tabs/custom/customtabid1'));
	$content = nl2br($this->getProduct()->$method());
	if(!empty($content)){
            $contentArr = explode(';', $content);
            echo '<ul  id="ingredientes_tab">';
            for ($i=0; $i<count($contentArr); $i++)
            {
                if($contentArr[$i] != '') echo '<li>' . $contentArr[$i] . '</li>'; 
            }
            echo '</ul>';
        }
}
?>